### PR TITLE
Fix issue of generating QRCode with console

### PR DESCRIPTION
**Pull request by jafaripur**
Related to session using in command line section. #9

### CODE REVIEW

**Comment by jafaripur** [comment]
Why this PL not merged!?

**Comment by ihipop** [comment]
Why this PL not merged!?
I was just want to make a  pull requests to this issue, and I find it was already exists.
It works,why this PL not merged!? for such a long time...

**Comment by jafaripur** [comment]
@ihipop Use this one, It's cool.

https://github.com/endroid/QrCode

**Comment by ihipop** [comment]
thank you for this recommendation.Stared.

**Pull request merged**
